# Generated by Django 4.2.4 on 2023-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Automotive', 'Automotive'), ('Tubular', 'Tubular'), ('Inverter', 'Inverter')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
