# Generated by Django 4.2.4 on 2023-08-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_customerproduct_category_c_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C_Orders',
        ),
    ]
