# Generated by Django 4.2.4 on 2023-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_delete_c_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='category',
            field=models.CharField(choices=[('Tubular', 'Tubular'), ('Automotive', 'Automotive'), ('Inverter', 'Inverter')], max_length=100),
        ),
    ]
