# Generated by Django 4.2.4 on 2023-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_alter_customerproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Tubular', 'Tubular'), ('Inverter', 'Inverter')], max_length=100),
        ),
    ]
