# Generated by Django 4.2.4 on 2023-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_alter_customerproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Tubular', 'Tubular'), ('Automotive', 'Automotive')], max_length=100),
        ),
    ]
