# Generated by Django 4.2.5 on 2023-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_alter_customerproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Automotive', 'Automotive'), ('Tubular', 'Tubular')], max_length=100),
        ),
    ]
