# Generated by Django 4.2.5 on 2023-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_alter_customerproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='description',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Tubular', 'Tubular'), ('Inverter', 'Inverter')], max_length=100),
        ),
    ]
