# Generated by Django 4.2.4 on 2023-08-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_itemrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrating',
            old_name='service',
            new_name='item',
        ),
    ]
