# Generated by Django 4.2.4 on 2023-08-31 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_service_itemrating_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.c_orders'),
        ),
    ]
