# Generated by Django 4.2.4 on 2023-09-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
