# Generated by Django 4.2.4 on 2023-09-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='PID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='UID',
            new_name='user',
        ),
    ]
