# Generated by Django 4.2.4 on 2023-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_pid_cart_product_rename_uid_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
