# Generated by Django 4.2.5 on 2023-09-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart'),
        ),
    ]
