# Generated by Django 4.2.5 on 2023-09-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_alter_customerproduct_category'),
        ('customer', '0016_alter_c_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.customerproduct'),
        ),
    ]
