# Generated by Django 4.2.5 on 2023-10-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_c_orders_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('thank you for your response', 'thank you for your response'), ('service engineer on the way', 'service engineer on the way'), ('having some delay come after a day', 'having some delay come after a day')], max_length=100)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.complaints')),
            ],
        ),
    ]
