# Generated by Django 4.2.5 on 2023-10-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_adminresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresponse',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.services'),
        ),
        migrations.AlterField(
            model_name='adminresponse',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.complaints'),
        ),
    ]
