# Generated by Django 4.2.5 on 2023-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_adminresponse_service_alter_adminresponse_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminresponse',
            name='response',
            field=models.CharField(max_length=100),
        ),
    ]
