# Generated by Django 4.2.5 on 2023-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_adminresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresponse',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
